### ISSUE TITLE
Fix the experiences section text hover

### ISSUE THREAD

**Issue by Prathamkrishna** [Prathamkrishna/personalproject#6]
while hovering over no text part, the text vanishes. it would be great if that could be fixed.

**Comment by shikharcodes** [comment]
I'll take a look @Prathamkrishna. 
Can you specify a bit more or maybe attach a screenshot of the problem's page? It'll be helpful.

**Comment by Prathamkrishna** [comment]
@shikharcodes  here you go, scroll the #experiences section on https://prathamkrishna.github.io/personalproject/
and when you hover over, the following happens:

![Screenshot (320)](https://user-images.githubusercontent.com/34184758/111328016-e5e16300-8693-11eb-8a5b-aa77bccd6c74.png)
![Screenshot (322)](https://user-images.githubusercontent.com/34184758/111328038-e974ea00-8693-11eb-99b1-447d3b6bb53d.png)

**Comment by shikharcodes** [comment]
Okay

**Comment by shikharcodes** [comment]
This problem is fixed now. But in order to do that, I had to remove the white background colour coming inside the box on hovering. So now, when we hover over the box and the text: 
- The box enlarges a bit.
- Text colour changes from white to red.
- The background colour remains black as set by me in order to solve the issue's problem.

And after the changes, it is looking good.
Hope this solution is okay @Prathamkrishna  :)

**Comment by shikharcodes** [comment]
Please give your views on the changes I've made so that I'll raise a pull request.

**Comment by Prathamkrishna** [comment]
@shikharcodes Alright sounds great! You can proceed with the pull request!

**Comment by Prathamkrishna** [comment]
Great! @shikharcodes
